// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radix.Infra.Data.Imp.Contexts;

namespace Radix.Infra.Migrations
{
    [DbContext(typeof(DbContextRadix))]
    [Migration("20180803160539_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adquirente");

                    b.Property<bool>("AntiFraude");

                    b.Property<int>("Bandeira");

                    b.Property<int>("LojaId");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Cartao");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Cartao", b =>
                {
                    b.HasOne("Radix.Domain.Models.Entities.Radix.Loja", "Loja")
                        .WithMany("Cartoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
