// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radix.Infra.Data.Imp.Contexts;

namespace Radix.Infra.Migrations
{
    [DbContext(typeof(DbContextRadix))]
    partial class DbContextRadixModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adquirente");

                    b.Property<bool>("AntiFraude");

                    b.Property<int>("Bandeira");

                    b.Property<int>("LojaId");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Cartao");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.RegistroTransacaoCielo", b =>
                {
                    b.Property<string>("MerchantOrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorizationCode");

                    b.Property<int?>("LojaId");

                    b.Property<string>("PaymentId");

                    b.Property<string>("ProofOfSale");

                    b.Property<string>("Tid");

                    b.HasKey("MerchantOrderId");

                    b.HasIndex("LojaId");

                    b.ToTable("RegistroTransacaoCielo");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.RegistroTransacaoStone", b =>
                {
                    b.Property<string>("OrderReference")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcquirerMessage");

                    b.Property<string>("AuthorizationCode");

                    b.Property<int?>("LojaId");

                    b.Property<string>("TransactionIdentifier");

                    b.Property<string>("TransactionKey");

                    b.Property<string>("UniqueSequentialNumber");

                    b.HasKey("OrderReference");

                    b.HasIndex("LojaId");

                    b.ToTable("RegistroTransacaoStone");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.Cartao", b =>
                {
                    b.HasOne("Radix.Domain.Models.Entities.Radix.Loja", "Loja")
                        .WithMany("Cartoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.RegistroTransacaoCielo", b =>
                {
                    b.HasOne("Radix.Domain.Models.Entities.Radix.Loja", "Loja")
                        .WithMany("RegistroTransacaoCielo")
                        .HasForeignKey("LojaId");
                });

            modelBuilder.Entity("Radix.Domain.Models.Entities.Radix.RegistroTransacaoStone", b =>
                {
                    b.HasOne("Radix.Domain.Models.Entities.Radix.Loja", "Loja")
                        .WithMany("RegistroTransacaoStone")
                        .HasForeignKey("LojaId");
                });
#pragma warning restore 612, 618
        }
    }
}
